import 'package:food_order/models/product_model.dart';

class global {
  static bool data = false;
  static List<Product> products = [
    Product(
      id: 1,
      name: "Pizza FastFood",
      price: 200.0,
      image: "assets/images/pizza.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 2,
      name: "Burger FastFood",
      price: 75.0,
      image: "assets/images/burger.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 3,
      name: "Hot-Dog FastFood",
      price: 125.0,
      image: "assets/images/hotdog.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 4,
      name: "Sandwich FastFood",
      price: 100.0,
      image: "assets/images/sandwich.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 5,
      name: "Samosa FastFood",
      price: 20.0,
      image: "assets/images/samosa.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 6,
      name: "Botlegourd Veg",
      price: 40.0,
      image: "assets/images/botlegourd.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 7,
      name: "Cabbage Veg",
      price: 29.0,
      image: "assets/images/cabbage.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 8,
      name: "Capsicum Veg",
      price: 50.0,
      image: "assets/images/capsicum.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 9,
      name: "Potato Veg",
      price: 40.0,
      image: "assets/images/potato.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 10,
      name: "Tomato Veg",
      price: 20.0,
      image: "assets/images/tomato.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 11,
      name: "Mango Fruit",
      price: 20.0,
      image: "assets/images/mango.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 12,
      name: "Pinaple Fruit",
      price: 100.0,
      image: "assets/images/pinaple.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 13,
      name: "Stawbery Fruit",
      price: 120.0,
      image: "assets/images/stabery.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 14,
      name: "Ghee Grocery",
      price: 520.0,
      image: "assets/images/amul.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 15,
      name: "Soap Grocery",
      price: 180.0,
      image: "assets/images/dettol.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 15,
      name: "Shampoo Grocery",
      price: 280.0,
      image: "assets/images/shampoo.png",
      quantity: 0,
      like: "false",
    ),
  ];
}
